// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJELFSZYTg8Sn8IRru9FpdptDqPzltKVs',
    appId: '1:305993929437:web:07b973aaebf827bbebc134',
    messagingSenderId: '305993929437',
    projectId: 'crypto-list-app-80614',
    authDomain: 'crypto-list-app-80614.firebaseapp.com',
    storageBucket: 'crypto-list-app-80614.appspot.com',
    measurementId: 'G-GKC61KG4X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvhGviHt8OoM0WRg-SI2ahuhy1HLdNofU',
    appId: '1:305993929437:android:cf042744f49887b5ebc134',
    messagingSenderId: '305993929437',
    projectId: 'crypto-list-app-80614',
    storageBucket: 'crypto-list-app-80614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8z8a7mBrc1xHhAfA-_tg35KeBSX4T6gs',
    appId: '1:305993929437:ios:abebf7d25cc04546ebc134',
    messagingSenderId: '305993929437',
    projectId: 'crypto-list-app-80614',
    storageBucket: 'crypto-list-app-80614.appspot.com',
    iosBundleId: 'com.example.cryptoCoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8z8a7mBrc1xHhAfA-_tg35KeBSX4T6gs',
    appId: '1:305993929437:ios:abebf7d25cc04546ebc134',
    messagingSenderId: '305993929437',
    projectId: 'crypto-list-app-80614',
    storageBucket: 'crypto-list-app-80614.appspot.com',
    iosBundleId: 'com.example.cryptoCoin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJELFSZYTg8Sn8IRru9FpdptDqPzltKVs',
    appId: '1:305993929437:web:facf9c549d9edde0ebc134',
    messagingSenderId: '305993929437',
    projectId: 'crypto-list-app-80614',
    authDomain: 'crypto-list-app-80614.firebaseapp.com',
    storageBucket: 'crypto-list-app-80614.appspot.com',
    measurementId: 'G-M9ZQP3E9D7',
  );
}
